2025-05-09 20:05:16,316 ERROR: Falha de autenticação SMTP ao enviar para nivioricardo@hotmail.com. Verifique: 1. Se a senha de aplicativo está correta 2. Se a autenticação de dois fatores está ativada 3. Se o acesso de aplicativos menos seguros está ativado (não recomendado). Erro detalhado: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 71dfb90a1353d-52c5375bcdcsm2055832e0c.25 - gsmtp') [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:98]
2025-05-09 20:05:18,084 ERROR: Falha de autenticação SMTP ao enviar para nivioricardo@hotmail.com. Verifique: 1. Se a senha de aplicativo está correta 2. Se a autenticação de dois fatores está ativada 3. Se o acesso de aplicativos menos seguros está ativado (não recomendado). Erro detalhado: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 71dfb90a1353d-52c536ff4e7sm2055214e0c.4 - gsmtp') [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:98]
2025-05-09 20:05:18,095 WARNING: Orçamento 26 salvo, mas emails falharam parcialmente [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:198]
2025-05-11 16:41:17,324 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:63]
2025-05-11 16:42:16,773 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-s2zi22m490n'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'SP'), ('produto', 'caneca'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa Futebol'), ('obs', 'Teste')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:120]
2025-05-11 16:42:16,783 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 16:42:17,415 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 16:42:18,756 ERROR: Erro inesperado ao enviar email: module 'os' has no attribute 'encode' [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:104]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 83, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 156, in send
    self.login()
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 210, in login
    self._login(self.credentials)
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 229, in _login
    self.smtp.login(self.user, password)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 652, in auth
    authobject(challenge).encode('ascii'), eol='')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'os' has no attribute 'encode'. Did you mean: 'fsencode'?
2025-05-11 16:42:19,986 ERROR: Erro inesperado ao enviar email: module 'os' has no attribute 'encode' [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:104]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 83, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 156, in send
    self.login()
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 210, in login
    self._login(self.credentials)
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 229, in _login
    self.smtp.login(self.user, password)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 652, in auth
    authobject(challenge).encode('ascii'), eol='')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'os' has no attribute 'encode'. Did you mean: 'fsencode'?
2025-05-11 16:42:20,003 WARNING: Orçamento 27 salvo, mas emails falharam parcialmente [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:196]
2025-05-11 16:43:04,201 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:63]
2025-05-11 16:43:24,636 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-s2zi22m490n'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'PA'), ('produto', 'caneca'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa Homem-Aranha'), ('obs', '')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:120]
2025-05-11 16:43:24,751 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 16:43:26,058 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 16:44:18,243 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:63]
2025-05-11 16:50:15,918 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:67]
2025-05-11 16:50:37,394 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-s2zi22m490n'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'PA'), ('produto', 'caneca'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa Homem-Aranha'), ('obs', '')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:125]
2025-05-11 16:50:37,529 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 16:50:38,570 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 16:50:40,312 ERROR: Erro inesperado ao enviar email: module 'os' has no attribute 'encode' [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:109]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 88, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 156, in send
    self.login()
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 210, in login
    self._login(self.credentials)
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 229, in _login
    self.smtp.login(self.user, password)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 652, in auth
    authobject(challenge).encode('ascii'), eol='')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'os' has no attribute 'encode'. Did you mean: 'fsencode'?
2025-05-11 16:50:40,372 WARNING: Orçamento 29 salvo, mas emails falharam parcialmente [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:193]
2025-05-11 16:52:28,524 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:67]
2025-05-11 16:52:50,738 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-s2zi22m490n'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'PR'), ('produto', 'caneca'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa BTS'), ('obs', 'teste')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:125]
2025-05-11 16:52:50,851 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 16:52:51,679 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
