2025-05-11 16:53:00,643 ERROR: Erro inesperado ao enviar email: 'ascii' codec can't encode character '\xe7' in position 731: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:109]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 88, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 172, in send
    return self._attempt_send(recipients, msg_strings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 178, in _attempt_send
    result = self.smtp.sendmail(self.user, recipients, msg_strings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe7' in position 731: ordinal not in range(128)
2025-05-11 16:53:00,908 WARNING: Orçamento 30 salvo, mas emails falharam parcialmente [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:193]
2025-05-11 16:57:57,518 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:75]
2025-05-11 16:58:06,329 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-s2zi22m490n'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'PE'), ('produto', 'caneca'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa BTS'), ('obs', 'te')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:177]
2025-05-11 16:58:06,497 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 16:58:07,372 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 16:58:15,267 ERROR: Problema de codificação ao enviar para ['juninhoboni@gmail.com']. Certifique-se que todos os textos estão em UTF-8. Erro: 'ascii' codec can't encode character '\xe7' in position 731: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:151]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 122, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 172, in send
    return self._attempt_send(recipients, msg_strings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 178, in _attempt_send
    result = self.smtp.sendmail(self.user, recipients, msg_strings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe7' in position 731: ordinal not in range(128)
2025-05-11 16:58:15,476 ERROR: Erro ao processar orçamento: name 'MAIL_GMAIL' is not defined [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:269]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 245, in enviar_orcamento
    [os.getenv(MAIL_GMAIL)],
               ^^^^^^^^^^
NameError: name 'MAIL_GMAIL' is not defined
2025-05-11 16:58:39,452 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:75]
2025-05-11 16:58:59,450 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-s2zi22m490n'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'PE'), ('produto', 'caneca'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa BTS'), ('obs', 'te')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:177]
2025-05-11 16:58:59,602 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 16:59:00,468 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 16:59:06,716 ERROR: Problema de codificação ao enviar para ['juninhoboni@gmail.com']. Certifique-se que todos os textos estão em UTF-8. Erro: 'ascii' codec can't encode character '\xe7' in position 731: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:151]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 122, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 172, in send
    return self._attempt_send(recipients, msg_strings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 178, in _attempt_send
    result = self.smtp.sendmail(self.user, recipients, msg_strings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe7' in position 731: ordinal not in range(128)
2025-05-11 16:59:08,606 ERROR: Problema de codificação ao enviar para ['michelepersonalizados2025@gmail.com']. Certifique-se que todos os textos estão em UTF-8. Erro: 'ascii' codec can't encode character '\xe7' in position 732: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:151]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 122, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 172, in send
    return self._attempt_send(recipients, msg_strings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 178, in _attempt_send
    result = self.smtp.sendmail(self.user, recipients, msg_strings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe7' in position 732: ordinal not in range(128)
2025-05-11 16:59:08,843 WARNING: Orçamento 32 salvo, mas emails falharam parcialmente [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:252]
2025-05-11 17:00:02,459 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:75]
2025-05-11 17:00:19,838 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-s2zi22m490n'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'PB'), ('produto', 'caderno'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa Homem-Aranha'), ('obs', '')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:174]
2025-05-11 17:00:19,986 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 17:00:20,835 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 17:00:29,317 INFO: Email enviado com sucesso para ['juninhoboni@gmail.com'] [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:129]
2025-05-11 17:00:32,207 INFO: Email enviado com sucesso para ['michelepersonalizados2025@gmail.com'] [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:129]
2025-05-11 17:03:41,152 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:75]
2025-05-11 17:03:59,081 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:75]
